import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import Link from 'next/link';
import ProductCard from '../components/ProductCard/ProductCard';
export async function getStaticProps() {
  const client = new ApolloClient({
     uri: 'https://api-ap-south-1.hygraph.com/v2/clbgfje3709ye01t111f421vw/master',
     cache: new InMemoryCache(),
  });
  const data = await client.query({
     query: gql`
     query Product {
      products {
        id
        price
        slug
        title
        image {
          url
        }
      }
    }
    
     `,
  });
  const allProducts = data.data.products;
  return {
     props: {
        allProducts,
     },
  };
 }
export default function Home({allProducts}: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
            <div className="product-container">
            {allProducts.map((product: any) => {
             return (
              <Link key={product.title} href={`products/${product.slug}`}>
              <ProductCard title={product.title} price={product.price} imgUrl={product.image.url}/>
              </Link>
                // <div className="product-card" key={product.id}>
                //    <Link href={`products/${product.slug}`}>
                //       <div className="product-img">
                //          <img src={product.image.url} alt={product.title} />
                //       </div>
                //    </Link>
                //    <div className="product-content">
                //       <h3>{product.title}</h3>
                //       <p>Rs {product.price}</p>
                //       <a className="btn">Add to cart 🛒</a>
                //    </div>
                // </div>
             );
          })}
            </div>
            </div>
  )
}
